solidus/backend/config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    put '/locale/set', to: 'locale#set', defaults: { format: :json }, as: :set_locale

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index, :new, :create]
      resources :promotion_code_batches, only: [:index, :new, :create] do
        get '/download', to: "promotion_code_batches#download", defaults: { format: "csv" }
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
      end
      resources :variants, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: :edit
    resources :stores, only: [:index, :new, :create, :edit, :update]

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]
    resources :store_credit_reasons, except: [:show]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_locations do
      resources :stock_movements, only: [:index]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

solidus/backend/app/controllers/spree/admin/return_authorizations_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class ReturnAuthorizationsController < ResourceController
      belongs_to 'spree/order', find_by: :number

      before_action :load_form_data, only: [:new, :edit]
      create.fails  :load_form_data
      update.fails  :load_form_data

      def fire
        action_from_params = "#{params[:e]}!"

        if @return_authorization.state_events.include?(params[:e].to_sym) &&
           @return_authorization.send(action_from_params)

          flash_message = { success: t('spree.return_authorization_updated') }
        else
          flash_message = { error: t('spree.return_authorization_fire_error') }
        end

        redirect_back(fallback_location: admin_order_return_authorizations_path(@order),
                      flash: flash_message)
      end

      private

      def load_form_data
        load_return_items
        load_reimbursement_types
        load_return_reasons
        load_stock_locations
      end

      # To satisfy how nested attributes works we want to create placeholder ReturnItems for
      # any InventoryUnits that have not already been added to the ReturnAuthorization.
      def load_return_items
        all_inventory_units = @return_authorization.order.inventory_units
        associated_inventory_units = @return_authorization.return_items.map(&:inventory_unit)
        unassociated_inventory_units = all_inventory_units - associated_inventory_units

        new_return_items = unassociated_inventory_units.map do |new_unit|
          Spree::ReturnItem.new(inventory_unit: new_unit).tap(&:set_default_amount)
        end
        @form_return_items = (@return_authorization.return_items + new_return_items).sort_by(&:inventory_unit_id)
      end

      def load_reimbursement_types
        @reimbursement_types = Spree::ReimbursementType.accessible_by(current_ability, :read).active
      end

      def load_return_reasons
        @reasons = Spree::ReturnReason.reasons_for_return_items(@return_authorization.return_items)
      end

      def load_stock_locations
        @stock_locations = Spree::StockLocation.order_default.active
      end
    end
  end
end

solidus/backend/app/views/spree/admin/return_authorizations/_form.html.erb
<% allow_return_item_changes = !@return_authorization.customer_returned_items? %>

<div data-hook="admin_return_authorization_form_fields">
  <table class="index return-items-table">
    <thead>
      <tr data-hook="rma_header">
        <th class="return-item-checkbox">
          <% if allow_return_item_changes %>
            <%= check_box_tag 'select-all' %>
          <% end %>
        </th>
        <th class="return-item-product"><%= Spree::Product.model_name.human %></th>
        <th class="return-item-state"><%= Spree::ReturnAuthorization.human_attribute_name(:state) %></th>
        <th class="return-item-charged"><%= Spree::ReturnItem.human_attribute_name(:charged) %></th>
        <th class="return-item-pre-tax-refund-amount wrap-text"><%= Spree::ReturnItem.human_attribute_name(:amount) %></th>
        <th class="return-item-reimbursement-type wrap-text"><%= Spree::ReimbursementType.model_name.human %></th>
        <th class="return-item-exchange-for"><%= Spree::ReturnItem.human_attribute_name(:exchange_variant) %></th>
        <th class="return-item-reason"><%= Spree::ReturnItem.human_attribute_name(:return_reason) %></th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :return_items, @form_return_items do |item_fields| %>
        <% return_item = item_fields.object %>
        <% inventory_unit = return_item.inventory_unit %>
        <% editable = inventory_unit.shipped? && !inventory_unit.exchange_requested? && allow_return_item_changes && return_item.reimbursement.nil? %>
        <tr>
          <td class="return-item-checkbox inventory-unit-checkbox">
            <% if editable %>
              <%= item_fields.hidden_field :inventory_unit_id %>
              <%= item_fields.check_box :_destroy, {checked: return_item.persisted?, class: 'add-item', "data-price" => return_item.amount}, '0', '1' %>
            <% end %>
          </td>
          <td class="return-item-product">
            <div class="variant-name"><%= inventory_unit.variant.name %></div>
            <div class="variant-options"><%= inventory_unit.variant.options_text %></div>
          </td>
          <td class="return-item-state">
            <span class="pill pill-<%= inventory_unit.state %>">
              <%= t(inventory_unit.state, scope: 'spree.inventory_states') %>
            </span>
          </td>
          <td class="return-item-charged">
            <%= return_item.display_amount %>
          </td>
          <td class="return-item-pre-tax-refund-amount">
            <% if editable %>
              <%= item_fields.text_field :amount, { class: 'refund-amount-input' } %>
            <% else %>
              <%= return_item.display_amount %>
            <% end %>
          </td>
          <td class="return-item-reimbursement-type">
            <% if editable %>
              <%= item_fields.select :preferred_reimbursement_type_id, @reimbursement_types.collect{|r|[r.name.humanize, r.id]}, {include_blank: true}, {class: 'custom-select fullwidth'} %>
            <% else %>
              <%= return_item.preferred_reimbursement_type.try(:name) %>
            <% end %>
          </td>
          <td class="return-item-exchange-for">
            <% if editable %>
              <%= item_fields.collection_select :exchange_variant_id, return_item.eligible_exchange_variants(@stock_locations), :id, :exchange_name, { include_blank: true }, { class: "custom-select fullwidth return-item-exchange-selection" } %>
            <% elsif return_item.exchange_processed? %>
              <%= return_item.exchange_variant.exchange_name %>
            <% end %>
          </td>
          <td class="return-item-reason">
            <% if editable %>
              <%= item_fields.select :return_reason_id, @reasons.collect{|r|[r.name, r.id]}, {include_blank: true}, {class: 'custom-select fullwidth'} %>
            <% else %>
              <%= return_item.return_reason.try(:name) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= f.field_container :amount do %>
    <%= t('spree.total_pre_tax_refund') %>: <span id="total_pre_tax_refund">0.00</span>
  <% end %>

  <%= f.field_container :stock_location do %>
    <%= f.label :stock_location_id, Spree::StockLocation.model_name.human %>
    <%= f.select :stock_location_id, @stock_locations.to_a.collect{|l|[l.name, l.id]}, {include_blank: true}, {class: 'custom-select fullwidth', "data-placeholder" => t('spree.select_a_stock_location')} %>
    <%= f.error_message_on :stock_location_id %>
  <% end %>

  <%= f.field_container :memo do %>
    <%= f.label :memo %>
    <%= f.text_area :memo, {style: 'height:100px;', class: 'fullwidth'} %>
    <%= f.error_message_on :memo %>
  <% end %>
</div>

solidus/backend/app/views/spree/admin/return_authorizations/edit.html.erb
<% content_for :page_actions do %>
  <% if @return_authorization.can_cancel? %>
    <li>
      <%= button_to t('spree.actions.cancel'), fire_admin_order_return_authorization_url(@order, @return_authorization, e: 'cancel'), method: :put, data: { confirm: t('spree.are_you_sure') } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Return Authorizations' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::ReturnAuthorization), spree.admin_order_return_authorizations_url) %>
<% admin_breadcrumb(
  """
    #{ @return_authorization.number }
    (#{ t(
      @return_authorization.state,
      scope: 'spree.return_authorization_states'
    ) })
  """
) %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @return_authorization } %>

<div data-hook="return-authorization-form-wrapper">
	<%= form_for [:admin, @order, @return_authorization] do |f| %>
	  <fieldset class="no-border-top">
	    <%= render partial: 'form', locals: { f: f } %>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button_tag t('spree.actions.update'), class: 'btn btn-primary' %>
        <%= link_to t('spree.actions.cancel'), admin_order_return_authorizations_url(@order), class: 'btn btn-primary' %>
      </div>
    </fieldset>
	<% end %>
</div>

solidus/backend/app/views/spree/admin/return_authorizations/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Return Authorizations' } %>

<% content_for :page_actions do %>
  <% if @order.shipments.any? &:shipped? %>
    <li>
      <% if can? :create, Spree::ReturnAuthorization %>
        <%= link_to t('spree.new_return_authorization'), new_admin_order_return_authorization_url(@order), class: 'btn btn-primary' %>
      <% end %>
    </li>
  <% end %>
<% end %>

<% admin_breadcrumb(plural_resource_name(Spree::ReturnAuthorization)) %>


<% if @order.shipments.any?(&:shipped?) || @order.return_authorizations.any? %>
  <table class="index">
    <thead data-hook="rma_header">
      <tr>
        <th><%= Spree::ReturnAuthorization.human_attribute_name(:number) %></th>
        <th><%= Spree::ReturnAuthorization.human_attribute_name(:state) %></th>
        <th><%= Spree::ReturnAuthorization.human_attribute_name(:total_excluding_vat) %></th>
        <th><%= Spree::ReturnAuthorization.human_attribute_name(:created_at) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @return_authorizations.each do |return_authorization| %>
        <tr id="<%= spree_dom_id(return_authorization) %>" data-hook="rma_row">
          <td><%= return_authorization.number %></td>
          <td>
            <span class="pill pill-<%= return_authorization.state %>">
              <%= t(
                return_authorization.state,
                scope: 'spree.return_authorization_states'
              ) %>
            </span>
          </td>
          <td><%= return_authorization.display_total_excluding_vat.to_html %></td>
          <td><%= pretty_time(return_authorization.created_at) %></td>
          <td class="actions">
            <% if can? :update, return_authorization %>
              <%= link_to_edit return_authorization, no_text: true, class: 'edit' %>
            <% end %>
            <% if can?(:destroy, return_authorization) && !return_authorization.customer_returned_items? %>
              <%= link_to_delete return_authorization, no_text: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div data-hook="rma_cannot_create" class="no-objects-found">
    <%= t('spree.cannot_create_returns') %>
  </div>
<% end %>

solidus/backend/app/views/spree/admin/return_authorizations/new.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Return Authorizations' } %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::ReturnAuthorization), spree.admin_order_return_authorizations_url) %>
<% admin_breadcrumb(t('spree.new_return_authorization')) %>


<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @return_authorization } %>
<%= form_for [:admin, @order, @return_authorization] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button_tag t('spree.actions.create'), class: 'btn btn-primary' %>
      <%= link_to t('spree.actions.cancel'), admin_order_return_authorizations_url(@order), class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>